### ISSUE TITLE
file.writable is not working for OSX

### ISSUE THREAD

**Issue by pbiecek** [iNZightVIT/Lite#16]
I do not know if OSX is worth testing
but for OSX in the function file.writable() the condition 
"unix"%in%.Platform$OS.type
is TRUE yet OSX stat does not have option -c
and in result one gets 
''stat: illegal option -- c''

**Comment by sharko666** [comment]
Thanks Pbiecek,
I did not think that it would ever run on a OSX and I do not have a mac to test the code on. I see what I can to make this stable.

Christoph
________________________________

**Comment by sharko666** [comment]
Hi Pbiecek,
I added "'Linux'%in%Sys.info()['sysname']" to file.writable. This function is anyway a very naive approach to test  for file permissions and should be rewritten. It now returns FALSE for all OS except a linux systems (I hope). On Linux system file permissions are tested. I also wrapped it in a tryCatch to make the function stable independently of OS. Please update to the current development branch to see the new code.

Thank you for your feedback, it is much appreciated.

Christoph
________________________________
From: Christoph Knapp
Sent: Tuesday, July 07, 2015 9:24
To: iNZightVIT/Lite; iNZightVIT/Lite
Subject: RE: [Lite] file.writable is not working for OSX (#16)

Thanks Pbiecek,
I did not think that it would ever run on a OSX and I do not have a mac to test the code on. I see what I can to make this stable.

Christoph
________________________________

**Comment by pbiecek** [comment]
Thanks, now it is working for OSX as well ;-)
