### ISSUE TITLE
Depends

### ISSUE THREAD

**Issue by pbiecek** [iNZightVIT/Lite#17]
In order to run 'Lite' application one needs to have required packages
Maybe they can be listed in ireadme.md, e.g.

library(devtools)
install_github("iNZightVIT/iNZightRegression")
install_github("iNZightVIT/iNZightMR")
install_github("iNZightVIT/iNZightPlots")
install_github("iNZightVIT/iNZightTS")

install.packages("gpairs")

**Comment by sharko666** [comment]
Good point Pbiecek,
I will update the readme file. That is something I like to fall behind in anyway. :-)

The full list of packages which need to be installed (+ dependencies) is

library(iNZightPlots)
library(iNZightTS)
library(iNZightMR)
library(markdown)
library(gpairs)
library(iNZightRegression)
library(RJSONIO)
library(survey)

Some of them might already be installed in your system.

Christoph
________________________________

**Comment by pbiecek** [comment]
Thanks
