### ISSUE TITLE
Missing packages

### ISSUE THREAD

**Issue by tell029** [iNZightVIT/Lite#18]
The `GGalley` package requires `reshape`, which isn't in the repo.

**Comment by sharko666** [comment]
Hi Tom,
yeah it was already installed and therefore was not reinstalled in specified lib. I installed it and pushed the new Lite version to git. There might be others missing too.

Christoph
________________________________

**Comment by tell029** [comment]
I think that's it. I'm now able to run the Lite app from a `docker` container built using a [`Dockerfile`](https://github.com/iNZightVIT/docker_images/blob/master/lite-test/Dockerfile), although I haven't tried anything other than a few simple plots.

**Comment by sharko666** [comment]
Hi Tom
How would you do that on the admin tool? I just updated the development container but the GGally package gives an error that it is not there. To test whether the GGally package is working try around with the compair pairs plot in Advanced -> Quick explore. It should work as the application would crash if a package is not installed.

Christoph
________________________________

**Comment by tell029** [comment]
It's not live yet - you'll need to wait for Rob to set up the admin page to
use the Dockerfile first.

On Monday, July 20, 2015, sharko666 <notifications@github.com> wrote:

> Hi Tom
> How would you do that on the admin tool? I just updated the development
> container but the GGally package gives an error that it is not there. To
> test whether the GGally package is working try around with the compair
> pairs plot in Advanced -> Quick explore. It should work as the application
> would crash if a package is not installed.
>
> Christoph
> ________________________________
> From: Tom Elliott [notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>]
> Sent: Monday, July 20, 2015 14:42
> To: iNZightVIT/Lite
> Cc: Christoph Knapp
> Subject: Re: [Lite] Missing packages (#18)
>
>
> I think that's it. I'm now able to run the Lite app from a docker
> container built using a Dockerfile<
> https://github.com/iNZightVIT/docker_images/blob/master/lite-test/Dockerfile>,
> although I haven't tried anything other than a few simple plots.
>
> —
> Reply to this email directly or view it on GitHub<
> https://github.com/iNZightVIT/Lite/issues/18#issuecomment-122735909>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/iNZightVIT/Lite/issues/18#issuecomment-122739578>.
>


-- 

*Tom Elliott*
