### ISSUE TITLE
Bug in footer

### ISSUE THREAD

**Issue by tell029** [iNZightVIT/Lite#2]
When the screen size shrinks (i.e., on a tablet), the logos get cut off.
My guess is that it's using some fixed-position and fixed-height CSS that isn't being altered by media queries. Possibly can blame bootstrap? :)

**Comment by cpi2025** [comment]
I used position  = "fixed" in the css because otherwise the footer wouldn't stick to the bottom of the page...

**Comment by tell029** [comment]
Yup. Maybe remove when screen size gets too small

**Comment by cpi2025** [comment]
Done. Thanks for the tip :)

*Chris Park*
