### ISSUE TITLE
Check functions working

### ISSUE THREAD

**Issue by tmelliott** [iNZightVIT/Lite#238]
[This file](https://github.com/iNZightVIT/Lite/blob/bac4d4c66dc6d56eb723041d635dfb28be0204e4/functions.R) contains some functions which were duplicated in `iNZightTools` - however, they are being deprecated [(fully deleted, actually)](iNZightVIT/iNZightTools#113) which will take effect in the next release of iNZightTools. 

So, could you check that the functions marked "to be deleted once iNZightTools is working" are using the versions specified in `functions.R`, and __not__ the functions in iNZightTools.

Several of these functions have been rewritten using `tidyverse` (e.g., `combine.levels()` is now `collapseLevels()`), so at some stage, we will need to change these over (but there's no rush yet) if/when Lite starts storing code history (as these tidyverse versions include the code).

One way to check things are working would be to---if you can run Lite locally---install the development version of iNZightTools:
```r
devtools::install_github("iNZightVIT/iNZightTools@bugfix/deprecate-functions")
```
and then check that the following work:
- combine factor levels
- form class intervals
- sample data
- search name(?) - honestly I don't know what this is used for :confused:

**Comment by T0ngChen** [comment]
Hi Tom, Lite already has code history stored and currently uses functions in InzightTools for most panels. Thanks for letting me know, I will check them out.

**Comment by T0ngChen** [comment]
The new version of InzightTools does not break anything. 

- combine.levels() and sample.data() are no longer used in Lite.
- form class intervals and search.name are still using the versions specified in functions.R.

I find that seach.name() is used in visualization panel and I have no idea either what this is used for...

Cheers, Tong

**Comment by tmelliott** [comment]
Fantastic, thanks Tong.
