### ISSUE TITLE
Is `gpairs` needed???

### ISSUE THREAD

**Issue by tmelliott** [iNZightVIT/Lite#25]
I thought Christoph used `GGally` instead of `gpairs` but maybe I'm wrong?

**Comment by tmelliott** [comment]
@ChristophKnapp @cpi2025

**Comment by cpi2025** [comment]
It looks like its used in the "Quick Explore" and "Model Fitting" modules.

**Comment by sharko666** [comment]
It might be an artefact frombefore I changed it to GGally. The plots should all use the ggpairs function. I probably just left it there.

**Comment by tmelliott** [comment]
@jcai849

**Comment by tmelliott** [comment]
8 year old issue lol - let's get this closed!
