### ISSUE TITLE
save plot as pdf

### ISSUE THREAD

**Issue by T0ngChen** [iNZightVIT/Lite#253]
the first page is blank

**Comment by chriswild** [comment]
Hi Tong.

This issue is because iNZightPlots does dotplots twice. Once to figure out window size dimensions so it can figure out how big to draw the dots, and then the real plot.
In desktop Tom has obviously figured out some way to only keep the 2nd plot in the pdf.

Best, Chris

**Comment by T0ngChen** [comment]
Hi Chris,

Thanks for letting me know, I've talked with Arden this Friday and he
pointed this out to me. I'll see whether I can replicate Tom's code to only
keep the 2nd plot.

Thanks, Tong

Tong Chen | PhD candidate
Department of Statistics
University of Auckland
