### ISSUE TITLE
Extend Imports Interface to Accept Further Specifications for Complex Filetypes

### ISSUE THREAD

**Issue by jcai849** [iNZightVIT/Lite#270]
Match [iNZight](https://github.com/iNZightVIT/iNZight) capacity for further specifications in import such as a dialog for choosing specific sheets from an `xlsx` file; or specific dataframe from an `rda` file

**Comment by tmelliott** [comment]
`attr(data, 'available.sheets')`

**Comment by tmelliott** [comment]
Example Excel doc with multiple sheets:
[sheet.xlsx](https://github.com/iNZightVIT/Lite/files/10703047/sheet.xlsx)
