### ISSUE TITLE
Check variable names when creating a new variable

### ISSUE THREAD

**Issue by daniel-barnett** [iNZightVIT/Lite#273]
This is low priority, but adding some checks to variable names in the `Create Variables` box.

For example, creating a variable with a dash (`test-variable`) crashes the Lite instance.

**Comment by tmelliott** [comment]
Or a space. See https://github.com/iNZightVIT/iNZight/blob/dev/R/iNZDataModWin.R#L910

**Comment by tmelliott** [comment]
@jcai849

**Comment by tmelliott** [comment]
This will be fixed by #277
