### ISSUE TITLE
Limit size of variable combinations (especially numeric)

### ISSUE THREAD

**Issue by tmelliott** [iNZightVIT/Lite#281]
If too many unique levels, Lite can/will crash.

**Comment by chrk623** [comment]
Don't seem to be able to replicate this, is this for when we do reshaping like long to wide?

**Comment by tmelliott** [comment]
I can't replicate it, but the description was fairly vague:
> For example, I inadvertently gave my students a large dataset, and some of them tried (not with my support) to make a categorical variable out of a continuous variable without using class intervals.

Perhaps they were using "Manipulate variables" > "Convert to categorical"? Otherwise, there's also "Dataset" > "Unite Columns" which lets you combine any two variables with `N` and `M` unique values, so it would probably be a good idea to check that `N x M < 100` or something.

**Comment by chrk623** [comment]
Just checked those, **"Convert to categorical"** is basically a `as.factor` and **"Unite Columns"** is kind of like a `paste` between columns with a `sep`. These don't seem to be the problem here.

Will come back to this..

**Comment by tmelliott** [comment]
Ignore this - @szmsu2011 is working on a refactor of the 'iNZightTools' package, and I'll get him to build in these types of constraints there rather than doing it in the GUI.
