### ISSUE TITLE
lite version

### ISSUE THREAD

**Issue by chrk623** [iNZightVIT/Lite#295]
@tmelliott

Is the production lite directly built from the master branch? I cant seem to find where its getting `lite.update` date and `lite.version`.

---

https://github.com/iNZightVIT/Lite/blob/91adaed39fd6d9261cf0931e9102f8bc5f0cf5cd/server.R#L69

https://github.com/iNZightVIT/Lite/blob/91adaed39fd6d9261cf0931e9102f8bc5f0cf5cd/VARS.default#L27

---

https://github.com/iNZightVIT/Lite/blob/91adaed39fd6d9261cf0931e9102f8bc5f0cf5cd/server.R#L68

https://github.com/iNZightVIT/Lite/blob/91adaed39fd6d9261cf0931e9102f8bc5f0cf5cd/VARS.default#L20

**Comment by tmelliott** [comment]
It gets written in the Dockerfile,
https://github.com/iNZightVIT/Lite/blob/dev/Dockerfile#L27-L28

**Comment by tmelliott** [comment]
Sorry - that's the date. The version doesn't get written from anywhere, but you should be able to read it from the DESCRIPTION file.
```r
desc <- read.dcf('DESCRIPTION')
version <- desc[, "Version"][[1]]
```

**Comment by chrk623** [comment]
thanks
