### ISSUE TITLE
Extend import options

### ISSUE THREAD

**Issue by tmelliott** [iNZightVIT/Lite#298]
For CSV files, some additional arguments to include:
- [ ] comment symbol
- [ ] delimiter

These need
- [ ] a UI in the 'import' panel (similar to the sheet selection)
- [ ] GET parameter handling (`lite.docker.stat.auckland.ac.nz/?url=location-of-data.com&comment=#&delim=;`)

**Comment by chrk623** [comment]
This is quiet difficult as Lite detects the file type automatically, we do not know the file type before hand (can't just show the new UI for CSV files only). Having this new UI just at the import panel before users importing a file might confuse the them. 

Unless we only have this for when importing from url but then i don't see google docs having delimiter problems? maybe just the comment symbol?

**Comment by tmelliott** [comment]
I'd imagine it would be somewhat similar to the Excel sheet selection. That is, once a user chooses a file, *then* show the new UI based on the file extension? In Desktop, there's an `advancedOptions()` method that gets called whenever the file changes (https://github.com/iNZightVIT/iNZight/blob/dev/R/iNZImportWin.R#L640). This then just provides additional inputs the user can specify.

But I admit I have little understanding of how complex this might be in Lite!

**Comment by tmelliott** [comment]
Hi @chrk623 
[New release of iNZightTools](https://github.com/iNZightVIT/iNZightTools/releases/tag/1.13.2) removes the default comment symbol (#) and instead uses a global option to configure,
```r
options(inzighttools.comment = "#")
```
It should be sufficient to update the 'iNZightTools' version in the `Dockerfile` to 1.13.2, ideally, once you have figured out how to add in an input for users to choose a comment character in CSV/Delimited files.

**Comment by chrk623** [comment]
Thanks @tmelliott 

I've spent some time figuring out how to show a **interactive table** for preview in a modal pop up but no luck, only managed to get it to work for a static html table.

I think given the current code base, might be easiet to just add a **Additional Options** button for the users to use after they've imported the data set.

**Comment by tmelliott** [comment]
I think it's okay for the data to get read multiple times - i.e., after importing the data (**which could fail, so try-catch needed?**) show extra options to re-read the data - if they can't be displayed in the main interface, then a button as you suggest should be fine.

**Comment by chrk623** [comment]
@tmelliott How did you allow users to change options like delimiter when the file is removed from `/tmp` after its being read in (`iNZightTools::smart_read`)? Don't you need to re-read the file with a new `delimiter` argument?

I'm trying to implement the preview data feature and the remove file after reading from URL problem but this seems to contradict each other.

**Comment by tmelliott** [comment]
There are two options, but given the 5MB size limit I'd probably just go with option 1.

1. Just call `smart_read()` with the URL each time (i.e., don't try to re-use the temp file). For small files, this has minimal overhead, and means we can tell people "your file is deleted from the disk immediately after import".
2. Set up a CRON task running every minute to delete all files more than 5 minutes old in the temp folder. This does have some risks, and would have extra overheads required in Lite's import logic to check the file still exists before trying to read it, etc.

**Comment by chrk623** [comment]
I mean when users upload the local file. Once it goes to preview, the file disappears. This happened yesterday but right now it seems to be OK 😂. Seems like its a shiny thing, not `smart_read`... I'll figure it out...

BTW managed to get the preview to work:
![image](https://user-images.githubusercontent.com/31636428/224598925-d79f2e80-351f-4669-acce-166968d62abe.png)

**Comment by tmelliott** [comment]
Very good on the preview.

I'm not sure about the file-deleting-for-preview thing - `smart_read()` automatically deletes the temp files on exit, and re-calling it will just re-download the file (which isn't a problem for <5MB files). If something else is going on, it's likely to do with what Lite and/or Shiny is doing ...

**Comment by chrk623** [comment]
Some minor things to add but the preview seems to work, if anyone has time, its at [features/extend-import](https://github.com/iNZightVIT/Lite/tree/features/extend-import). 

In case I missed any test cases.

**Comment by chrk623** [comment]
Hey @tmelliott 

- Preview mode is complete
- Importing from URL now uses `iNZightTools::smart_read` 
- Fixed #305, Lite will now show a more friendly message when importing failed

Kind of a big update, would be great if you could review it incase I missed any test cases for the preview mode.

[features/extend-import](https://github.com/iNZightVIT/Lite/tree/features/extend-import)

**Comment by tmelliott** [comment]
Thanks Charco - looks good, my only question is - how much work would it be to make the preview work for URLs too? Is there any reason why these use different systems? `iNZightTools::smart_read()` can handle a file path or URL and all the same arguments either way, so the only difference is value being passed in (a temporary file location, or a URL).

**Comment by chrk623** [comment]
Its not difficult but sometimes the URL don't contain the file type  which is needed the preview.

**Comment by chriswild** [comment]
Tom, can the smart-tread itself (be made to) report some sort of error/warning that Charco can check for whenever it encounters a filetype for where can’t do a preview? -- Chris

**Comment by tmelliott** [comment]
@chriswild I think the issue is more that the interface uses the file extension to do a bit of guesswork around what to display rather than what's returned - I'm pretty sure `smart_read()` will just fail if there's no extension (in Desktop, the user just has to choose something from the dropdown to override).

**Comment by chrk623** [comment]
>  I'm pretty sure `smart_read()` will just fail if there's no extension (in Desktop, the user just has to choose something from the dropdown to override).

In this case, then It should be good, same as how Lite works. I will make some changes to the preview.

---

I also realized that I didn't let the users select file type when the imported data is a binary file (I thought that was the behaviour in desktop iNZight but apparently not), need to change this too. Got mixed up with the *"Advanced Options"*.

**Comment by chrk623** [comment]
I see that railway watches the `fearues/extend-import` branch, I'll let you guys know once I've made these changes.

**Comment by chriswild** [comment]
Hi Both, I think anything important that “just fails” is dangerous (depending on what “just fails” means). At the very least  should always at least return a “I can’t do this” message

**Comment by tmelliott** [comment]
In Desktop, "just fails" gives you the messaging saying "Unable to generate preview" or something, and generally has options to change file type / delimiter / etc. I think Charco is working on something similar in Lite re his last comment.

**Comment by chrk623** [comment]
> Hi @chrk623 - do you remember if there was any work left to do on this? I remember we had some issues with the deployment, but I can't remember if we fixed them ... 😬
> 
> EDIT: I think it was just the `get.data.from.URL()` function? If so, was there anything left to do for this issue? Otherwise it can be closed!

Yes, I think this is fixed already. Importing part is done, still need to do the query parameter part, I might be a bit of work so lets just push this out first and leave this issue open for now?

**Comment by tmelliott** [comment]
Moved into a separate issue so this one can be closed. @chrk623 could you leave a comment in #322 with an outline of what needs to be done, for future reference?
