### ISSUE TITLE
Data lifecycle

### ISSUE THREAD

**Issue by tmelliott** [iNZightVIT/Lite#304]
What is the lifecycle of uploaded data into Lite?

- [ ] Where is the uploaded file stored (e.g., CSV files)?
- [ ] Where does the imported data go (after loading into Lite)?
- [ ] At what point, if any, does the data get deleted?
- [ ] And if not, why not?

**Comment by chrk623** [comment]
Uploading local files:
- Goes to `/tmp/....`
- Deleted when the shiny session is closed

Importing from URLs:
- Downloaded to `/tmp/iNZight/Imported`
- Not deleted at all, maybe when the server restarts?
- #298 will switch to using `iNZightTools::smart_read` so the file won't be stored. The "remove data" module will also be removed.

**Comment by tmelliott** [comment]
Great - so 'shiny session' is the **user's** session, and not the shiny instance running on the server? i.e., when I close the browser window, the data vanishes?

For URLs, if we can move away from using temp files, then we should be sorted! I'll write this out for the 'Help' section of "Import data" so we are transparent with users, and that should be enough to close this issue.

**Comment by chrk623** [comment]
Should be when user closes the browser assuming the server launches a new instance per user.

**Comment by tmelliott** [comment]
I'd like to put together a short information page/modal that explains the lifecycle of data uploaded (from file or URL) - both for our future reference and users.

**Comment by tmelliott** [comment]
https://github.com/iNZightVIT/Lite/wiki/Data-lifecycle
