### ISSUE TITLE
Behaviour change: do not auto-choose V1 as the first variable

### ISSUE THREAD

**Issue by tmelliott** [iNZightVIT/Lite#308]
- Often, the first variable is some kind of an index or ID variable and makes little sense to plot
- Proposal: set Variable 1 to 'none' by default (like the other variables, and in line with how Desktop behaves)

Pros:
- faster landing on Visualize tab (currently it lags while loading that first graph)
- no ugly/unuseful/unnecessary first graph

Cons:
- different behaviour, but not drastically 

Thoughts, @chriswild? (Hopefully this sends you an email you can reply to...)

**Comment by chriswild** [comment]
Hi Tom, As a general rule I like something to appear immediately whenever we have something sensible to show

But I think your argument that the first variable is often/usually not something sensible to show, and it also causes problems (e.g. too many categories)

So I’m convinced.

Best, Chris

From: Tom Elliott ***@***.***>
Sent: Tuesday, 14 March 2023 1:09 pm
To: iNZightVIT/Lite ***@***.***>
Cc: Chris Wild ***@***.***>; Mention ***@***.***>
Subject: [iNZightVIT/Lite] Behaviour change: do not auto-choose V1 as the first variable (Issue #308)


  *   Often, the first variable is some kind of an index or ID variable and makes little sense to plot
  *   Proposal: set Variable 1 to 'none' by default (like the other variables, and in line with how Desktop behaves)

Pros:

  *   faster landing on Visualize tab (currently it lags while loading that first graph)
  *   no ugly/unuseful/unnecessary first graph

Cons:

  *   different behaviour, but not drastically

Thoughts, @chriswild<https://github.com/chriswild>? (Hopefully this sends you an email you can reply to...)

**Comment by tmelliott** [comment]
Won't change (at this stage) as it will create more issues than it solves.

**Comment by tmelliott** [comment]
Decided we wont fix this - instead will hold until we connect with new TS functionality.

**Comment by chrk623** [comment]
Turns out to be some work. The visualize module is huge and a bit messy. Also, there is a BUG here, currently it uses `"none"` in variable2 for a placeholder but if there is actually a "none" column in the uploaded dataset, it dosen't work as expected.

**Comment by tmelliott** [comment]
Yep - there's a lot going on there..
Don't spend more than 2 hours trying to figure this out - if it's more complicated that that, we'll leave it.

As for the bug, would it be easy to relabel the tabs to "- none -" or something less likely to be a variable?

**Comment by chrk623** [comment]
I think there is a `selected = NULL` option for `selectInput`. I'll fix this along with "auto-choose V1" before the new release. If not we can leave it as an enhancement, I can't estimate the time for this.

**Comment by tmelliott** [comment]
Let's not bother for now - it's too likely it'll have unanticipated side-effects, so we'll work on it after the summer release.
