### ISSUE TITLE
Should iNZight Lite logo link to inzight.nz?

### ISSUE THREAD

**Issue by tmelliott** [iNZightVIT/Lite#310]
This is the current behaviour. However, a few times I've clicked it to get back to the landing page and it throws me away from Lite, which is bad UX. I propose clicking the logo (on the left of the header) does nothing, or goes to the About page. 

@chriswild @chrk623

**Comment by chrk623** [comment]
To which landing page? Lite or iNZight website?

We can probably make go to [inzight.nz](inzight.nz) in a new tab or window?

**Comment by tmelliott** [comment]
Indeed - I say we just disable the link as there's no obvious 'home' page for Lite..
