### ISSUE TITLE
Update to iNZightTools 2.0.0

### ISSUE THREAD

**Issue by tmelliott** [iNZightVIT/Lite#321]
Some changes to function and argument names. See [changelog](https://github.com/iNZightVIT/iNZightTools/blob/dev/NEWS.md).

**Comment by chrk623** [comment]
https://github.com/iNZightVIT/iNZightTools/blob/dev/NEWS.md

**Comment by chrk623** [comment]
TODO:

- [ ] Seperate module seems to be broken before iNZightTools 2.0.0
- [ ] Error with unite module when using `iNZightTools::combine_vars`. https://github.com/iNZightVIT/iNZightTools/issues/218
- [ ] Merge module needs some code refactoring?
- [ ] `iNZightTools::convert_to_datetime` don't seem to support all
```R
"year month date",
"year month date Hour Minute Second",
"year month date Hour Minute Second pm/am",
"day month year",
"day month year Hour Minute Second",
"day month year Hour Minute Second pm/am",
"Unix timestamp (secs from 1970)"
```

**Comment by chrk623** [comment]
@tmelliott 

I think the following options in the datetime module is a bit ambigious, what do you think?
```
"year month date",
"year month date Hour Minute Second",
"year month date Hour Minute Second pm/am",
"day month year",
"day month year Hour Minute Second",
"day month year Hour Minute Second pm/am",
"Unix timestamp (secs from 1970)"
  ```
 and i'm pretty sure `"year month date"` should be `"year month day"`. Also, these options will assume that the date seperator is `-` and time seperator is `:`? Probably better to show `year-month-day`?

There are a lot of possibilities here, whats your take on this?

**Comment by tmelliott** [comment]
Ah yes, 'date' should probably be 'day'!

The format is actually flexible - the values are just the order, so e.g., 'year month day' should parse values "2024-02-15" or "2024 feb 15" or "24/02/15".

**Comment by chrk623** [comment]
Oh wow, I didn't know `lubridate::parse_date_time` is smart enough to guess the seperators and month type ...etc Thanks.

The update for iNZightTools 2.0.0 seems to be complete now, I'll wait for https://github.com/iNZightVIT/iNZightTools/issues/219 and do some more testing before pushing.
