### ISSUE TITLE
Refactor navigation menu to be reactive to config

### ISSUE THREAD

**Issue by tmelliott** [iNZightVIT/Lite#345]
Currently, menu is static. When LITE_CONFIG modified, a very manual process is used to remove options, etc.

Ideally, the menu would be generated by a function that takes a 'config'/'version' argument and spits out the appropriate menu.

Here's my guess of what things might look like:

```r
generate_menu <- function(version) {
  import_tabs <- list(...)
  if (!is.null(version) && version == "CAS") {
    import_tabs <- import_tabs[!names(import_tabs) %in% 'export']
  }
  import_tabs <- do.call(...)

  # ... repeat for all menus

  list(
    tabPanel("File", import_tabs), 
    ...
  )
}

delete_tabs <- function() {
  # Either programmatically look up tabs and remove them
  # or store a list of tab names, and cycle through them to delete...
}

observeEvent(session$userData$LITE_VERSION, { # this might work?
  menu <- generate_menu(session$userData$LITE_VERSION)
  delete_tabs() # how?
  
  # add new tabs
  lapply(menu, \(x) insertTab(inputId = "selector", x)
})
```

**Comment by chrk623** [comment]
Hey Tom, I've made a branch `features/dynamic-config`, but I think you've changes some tabs since last time, so I'm not sure which tabs you want shown in `CAS`. Following on with you code, the tabs shown seems to be different from what is on census at school.

**Comment by tmelliott** [comment]
I vaguely remember something being incorrectly disabled somewhere, so it was showing up even though it shouldn't. Having things done this way, it is now very easy to see what tabs get disabled so we can adjust as necessary.
