### ISSUE TITLE
Remove maps module

### ISSUE THREAD

**Issue by chrk623** [iNZightVIT/Lite#376]
@tmelliott thoughts?

**Comment by tmelliott** [comment]
Does it still work?

**Comment by chrk623** [comment]
Can't get it to install locally, but it dont seem to work in the dev enviornment.

**Comment by tmelliott** [comment]
Yeah all the packages are dead/migrated into a new collection. I tried, it doesn't seem to be working, so yep - go ahead and comment it all out.
